In [15]:
# 1  Create a 1d numpy array with value from 0 to 9 
import numpy as np 
z=np.array(1)
z

array(1)

In [17]:
#2 create 3 x 3 numpy array filled with zeros 
c=np.zeros([3,3])
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#3 create 4 X 4  numpy array filled with ones 
c=np.full([4,4],1)
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
#4 create 5 X 5  identity matrix 
# method 1 
c=np.identity(5,dtype=int)
c
#method 2
c=np.eye(5)
c

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
# 5 create a 2D array with random integers between 10   and 50
a=np.array([[10,51,10],[10,20,30]])
a
np.ndim(a)

2

In [34]:
# 6 create a 3D array and find the shape,size, and dimension 
a=np.array([[[10,51,10],[10,20,30],[10,20,50]]])
a
print(np.ndim(a))
print(np.shape(a))
print(np.size(a))

3
(1, 3, 3)
9


In [35]:
# 7 create a 1D array of 10 equally spaced numbers between 1 & 5 
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
# 8 convert a list into a numpy array
a=[1,2,3,4,5,6,7,8]
b=np.array(a)
print(b)
type(b)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [44]:
# 9 create a numpy arrray of 100 random floats betweeen 0 &1
a=np.arange(100,dtype=float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [50]:
# 10  Reshape a 1D array of 12 elements into a 3 X 4 matrix 
a=np.arange(12)
a
print(a.ndim)
b=a.reshape(3,4)
print(b)

1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
# 11 flatern a 2D array into 1D 
a=np.array([[1,2,3],[1,2,5]])
a
#method 1 
b=a.reshape(-1)
b
#method 2 
a.flatten()


array([1, 2, 3, 1, 2, 5])

In [62]:
# 12 create a boolean array where  all values are true 
a=np.full((5,5),True)
a

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [63]:
# 13 create an array with values[1,2,3] and multiply each element by 5 
a=np.array([1,2,3])
print(a*5)

[ 5 10 15]


In [72]:
#14 Access the element at the 2nd row and 3rd column in a 3 x 3 array 
a=np.array([[2,4,3,4],[3,4,5,6],[1,2,3,4]])
a
a[1:]

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [74]:
# 15 slice the first two rows and first two columns from a 3 X 3 array
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = a[:2, :2]

print("Original array:\n", a)
print("Sliced array:\n", b)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced array:
 [[1 2]
 [4 5]]


In [76]:
# 16 Add two arrays of the same shape 
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
print(a+b)

array([ 2,  4,  6,  8, 10, 12])

In [82]:
# 17 Subtract  two arrays of the same shape 
a=np.array([1,2,3,4,5,6])
b=np.array([10,20,30,40,50,60])
print(a-b)

[ -9 -18 -27 -36 -45 -54]


In [83]:
# 18 Multiply  two arrays element wise  
a=np.array([1,2,3,4,5,6])
b=np.array([10,20,30,40,50,60])
print(a*b)

[ 10  40  90 160 250 360]


In [93]:
# 19 Perfrom matrix multiplication using @ or np.dot()
a=np.array([1,2,3,4,5,6])
b=np.array([10,20,30,40,50,60])
print(a*b)

[ 10  40  90 160 250 360]


In [89]:
# 19 Perfrom matrix multiplication using @ or np.dot()
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[10],[20],[30]])

# Method 1: Using @ operator
result = a @ b
result
# Method 2: Using np.dot()
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[140]
 [320]]


In [94]:
# 20 find the mean ,median ,and standard deviation of an array  
a=np.array([1,2,3,4,5,6,7,8,9,5,6,2,3,6,5,2,6])
print(np.mean(a))
print(np.median(a))
print(np.std(a))

4.705882352941177
5.0
2.2166404331078553


In [102]:
#21 sort a numpy array in ascending and descending order 
a=np.array([2,5,8,7,5,5,58,55,58,5,6,6])
b=(np.sort(a))
print("Ascending:",b)
c = np.sort(a)[::-1]
print("Descending:", c)


Ascending: [ 2  5  5  5  5  6  6  7  8 55 58 58]
Descending: [58 58 55  8  7  6  6  5  5  5  5  2]


In [112]:
#22 replace all elements greater than 50 in with 50 in an array
a=np.arange(1,100)
a
a[a >= 50] = 50
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50]


In [122]:
#23 stack two arrays vertically using vstack()
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,3,1],[4,9,1]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 1],
       [4, 9, 1]])

In [123]:
#24 stack two arrays vertically using vstack()
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,3,1],[4,9,1]])
np.hstack((a,b))

array([[1, 2, 3, 1, 3, 1],
       [4, 5, 6, 4, 9, 1]])

In [130]:
#25 split a 1D arrray into 3 equal parts 
a=np.array([4,2,4,5,5,6,6,2,3])
a
np.split(a,3)

[array([4, 2, 4]), array([5, 5, 6]), array([6, 2, 3])]

In [142]:
#26 Create a 5 x 5 array with a border of 1s and all 0s inside 
a = np.ones((5, 5), dtype=int)   # Create a 5x5 array of 1s
print(a)
a[1:-1, 1:-1] = 0   # Set the inner 3x3 block to 0
print(a)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [138]:
#27 Extract all even numbers from a numpy array 
a=np.arange(2,101,2)
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [151]:
# 28 Count how many values are greater than a certain number 
a=np.array([1,2,3,8])
# Count values greater than 2
count = np.sum(a > 2)
print("Count of values > 2:", count)


Count of values > 2: 2


In [162]:
#29 find the index of the maxixmum and minimum element in an array 
a=np.array([1,2,3,2,5,8,9,6,3,6,8])
#b=np.max(a)
import numpy as np
min_index = np.argmin(a)
max_index = np.argmax(a)
print("Minimum value index:", min_index)
print("Maximum value index:", max_index)


Minimum value index: 0
Maximum value index: 6


In [163]:
# 30 check if two arrrays are equal 
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1,3,1],[4,9,1]])
np.array_equal(a,b)

False

In [166]:
#31 get the unique values from an array 
a=np.array([4,4,4,4,4,45,55,88,585,55,8585,8,5,5,8,5,58])
np.unique(a)

array([   4,    5,    8,   45,   55,   58,   88,  585, 8585])

In [172]:
#32 replace nan values in an array with 0
#a=np.array([4,4,4,4,nan,nan,nan,nan,nan,4,4,5,5,5,8,8,5,8,5,5,8,5,8,5,8,5,5,8,5,5,8])
#np.replace(nan,0)
a = np.array([4, 4, 4, 4, np.nan, np.nan, np.nan, np.nan, np.nan, 4, 4, 5, 5, 5, 8, 8, 5, 8, 5, 5, 8, 5, 8, 5, 8, 5, 5, 8, 5, 5, 8])
# Replace NaNs with 0
a[np.isnan(a)] = 0
print(a)

[4. 4. 4. 4. 0. 0. 0. 0. 0. 4. 4. 5. 5. 5. 8. 8. 5. 8. 5. 5. 8. 5. 8. 5.
 8. 5. 5. 8. 5. 5. 8.]


In [1]:
# 33 Generate a 3 X 3 array with values from a normal distribution 
import numpy as np
arr = np.random.normal(loc=0, scale=1, size=(3, 3))
print(arr)


[[-0.75029547  0.31737756  0.19900955]
 [ 0.16730271 -0.72231871 -0.13626321]
 [ 0.84387571  1.51144091  1.40598491]]


In [24]:
#34 Create a 4D array and print its shape and dimensions 
import numpy as np 
a=np.array([[[[1,2,3],[1,4,5]],[[8,9,5],[4,5,8]]]])
print(a)
print(np.shape(a))
print(np.ndim(a))

[[[[1 2 3]
   [1 4 5]]

  [[8 9 5]
   [4 5 8]]]]
(1, 2, 2, 3)
4


In [25]:
# 35 Reverse a 1D array using slicing 
a=np.array([1,2,5,4,6,8,9,5,8,5])
print(a[::-1])

[5 8 5 9 8 6 4 5 2 1]


In [40]:
#36  use broadcasting to add 1D array to each row of a 2D array 
a=np.array([1,2,4,5,7,8,8])
b=np.array([[4,5,8,9,7,8,8],[2,4,4,4,7,7,8]])
print('first array :\n',a,'\n')
print("second array :\n",b,'\n')
print("first array + second array \n",a+b)


first array :
 [1 2 4 5 7 8 8] 

second array :
 [[4 5 8 9 7 8 8]
 [2 4 4 4 7 7 8]] 

first array + second array 
 [[ 5  7 12 14 14 16 16]
 [ 3  6  8  9 14 15 16]]


In [47]:
#37 Create a 10 X 10 matrix with values from 1,100
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
#38 Normalize an array so that its values range between 0 and 1 
arr = np.random.normal(loc=0, scale=1,size=10)
print(arr)

[-0.43642624 -0.78246252 -1.52705093 -0.81065668 -1.1989079  -0.00480636
  0.81809637  0.66266443  0.20378763  2.99906331]


In [87]:
#39 write a function that takes a numpy array and returns the row with the maximum sum 
def array():
    a = int(input("Enter the value of a: "))
    b = int(input("Enter the value of b: "))
    d = int(input("Enter the value of d: "))
    return a, b, d
a, b, d = array()
print(f"The value of a is {a}, the value of b is {b}, and the value of d is {d}")
#h=print(np.array([{a},{b},{d}]))

def row_with_max_sum(arr):
    row_sums = arr.sum(axis=1)       # Sum along rows
    max_row_index = np.argmax(row_sums)  # Index of row with max sum
    return arr[max_row_index]        # Return the row
h=np.array([[1,2,3,4,5],[4,5,6,7,8],[45,85,78,55,89]])
result = row_with_max_sum(h)
print("Row with maximum sum:", result)

Enter the value of a:  5454
Enter the value of b:  54
Enter the value of d:  566


The value of a is 5454, the value of b is 54, and the value of d is 566
Row with maximum sum: [45 85 78 55 89]


In [88]:
# 40 Use boolean indexing to select values less than a threshold  
arr = np.array([10, 25, 5, 30, 12, 7, 50, 3])
threshold = 15   # threshold any random number 
result = arr[arr < threshold]
print("Original array:", arr)
print(f"Values less than {threshold}:", result)


Original array: [10 25  5 30 12  7 50  3]
Values less than 15: [10  5 12  7  3]


In [89]:
#41 Creeate a checkerboard pattern (like a chessboard) using numpy
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)

# Fill alternate squares with 1s to create checkerboard pattern
checkerboard[1::2, ::2] = 1  # rows 1,3,5,7 → columns 0,2,4,6
checkerboard[::2, 1::2] = 1  # rows 0,2,4,6 → columns 1,3,5,7

print("Checkerboard pattern:\n", checkerboard)


Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [92]:
#42 Find the common elements between 2 arrays
a=np.array([1,2,5,4,8,7,8,5,5,8,5,8])
b=np.array([1,5,8,9,6,4,5,5,5,8,5,8])
np.intersect1d(a,b)

array([1, 4, 5, 8])

In [11]:
#43 use np.where () to replace negative values with 0 and keep others the same 
a=np.array([1,-2,-5,4,-8,-7,8,-5,5,-8,-5,-8])
b=np.where(a<0,0,a)
b

array([1, 0, 0, 4, 0, 0, 8, 0, 5, 0, 0, 0])

In [15]:
#44 Tile a small array into a larger matrix using np.title()
a=np.array([1,2,5,4,8,7,8,5,5,8,5,8])
np.tile(a,(2,2))

array([[1, 2, 5, 4, 8, 7, 8, 5, 5, 8, 5, 8, 1, 2, 5, 4, 8, 7, 8, 5, 5, 8,
        5, 8],
       [1, 2, 5, 4, 8, 7, 8, 5, 5, 8, 5, 8, 1, 2, 5, 4, 8, 7, 8, 5, 5, 8,
        5, 8]])

In [22]:
#45 Broadcast a 1D array across a 3D array 
import numpy as np 
a=np.array([1,2,3])
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
np.ndim(b)
print(a+b)

[[[ 2  4  6]
  [ 5  7  9]
  [ 8 10 12]]]


In [23]:
#46 use np.argmax() to find the index of the largest element along an axis
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
np.argmax(b)

8

In [26]:
#47 Generate a random seed and create reproducible random arrays
import numpy as np

# Set the seed for reproducibility
np.random.seed(42)

# Generate a random array
random_array = np.random.rand(5)  # 5 random numbers between 0 and 1

print("Random Array:", random_array)


Random Array: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [28]:
#48 Find the pair of values with the minimum absolute diff from an array 
import numpy as np
a = np.array([10, 3, 20, 9, 7, 4])
sorted_a = np.sort(a)
# Step 2: Compute absolute differences between consecutive elements
diffs = np.abs(np.diff(sorted_a))
# Step 3: Find the index of the minimum difference
min_index = np.argmin(diffs)
# Step 4: Get the pair with the smallest difference
pair = (sorted_a[min_index], sorted_a[min_index + 1])
print("Array:", a)
print("Sorted:", sorted_a)
print("Pair with minimum absolute difference:", pair)


Array: [10  3 20  9  7  4]
Sorted: [ 3  4  7  9 10 20]
Pair with minimum absolute difference: (3, 4)


In [29]:
#49 use slicing to flip a 2D array horizontally and vertically 
import numpy as np

# Sample 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
horizontal_flip = a[:, ::-1]
print("Horizontally Flipped:\n", horizontal_flip)
vertical_flip = a[::-1, :]
print("Vertically Flipped:\n", vertical_flip)


Horizontally Flipped:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Vertically Flipped:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [30]:
#50 Create a 3D array and compute its sum along different axes 
import numpy as np

# Create a 3D array of shape (2, 3, 4)
a = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9,10,11,12]],

    [[13,14,15,16],
     [17,18,19,20],
     [21,22,23,24]]
])

print("3D Array:\n", a)
print("Shape:", a.shape)


3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [2]:
#51  Find the common elements between 2 arrays
import numpy as np
a=np.array([1,2,5,4,8,7,8,5,5,8,5,8])
b=np.array([1,5,8,9,6,4,5,5,5,8,5,8])
np.setxor1d(a,b)

array([2, 6, 7, 9])

In [35]:
#52  print numbers between 10 ,50 with step value 5 .
import numpy as np
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# 53 create a numpy array with numpy module of integer and float datatype 
import numpy as np 
d=np.array([1,2,3],dtype=int)
d
import numpy as np 
d=np.array([1,2,3],dtype=float)
d

In [ ]:
# 54 create arrays of 0,1,2,3,4 dimensions and check their  shape ,size and dimensions 
a=np.array([[1,2,3,4],[1,2,3,4],[5,8,7,9],[7,8,9,6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

In [ ]:
#55 create a 0,1,2,3,4 dimensional array and print their shape , size and dimension 
import numpy as np

# 0D array (scalar)
a0 = np.array(5)
print("0D Array:", a0)
print("Shape:", a0.shape)
print("Dimensions:", a0.ndim)
print("Size:", a0.size)
print()

# 1D array
a1 = np.array([1, 2, 3])
print("1D Array:", a1)
print("Shape:", a1.shape)
print("Dimensions:", a1.ndim)
print("Size:", a1.size)
print()

# 2D array
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", a2)
print("Shape:", a2.shape)
print("Dimensions:", a2.ndim)
print("Size:", a2.size)
print()

# 3D array
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", a3)
print("Shape:", a3.shape)
print("Dimensions:", a3.ndim)
print("Size:", a3.size)
print()

# 4D array
a4 = np.array([[[[1], [2]], [[3], [4]]]])
print("4D Array:\n", a4)
print("Shape:", a4.shape)
print("Dimensions:", a4.ndim)
print("Size:", a4.size)

In [ ]:
# 56 create a 2*2 and 3*3 identity mtrix using 2 different methods
import numpy as np 
#i1=np.array([[1,0,0],[0,1,0],[0,0,1]])
#i1
a=np.eye(5,6)
a


In [ ]:
# 57 Generate 20 random integers between 1 and 100
b=np.random.randint(1,100,20)
b

a=np.array([[0,0,0np.zeros((2,5))
np.random.randint(1,100,25)
g= np.round(np.random.uniform(1,200,25),5)
g,0,0],[0,0,0,0,0]])
np.sort(b)
np.transpose(b)
b=np.random.randint(1,101,15)
np.argsort(b)

In [ ]:
# 58 create arrays of 0,1,2,3,4 dimensions and check their shape,size and dimensions
z=np.array(1)    #0Dim array
print(z.shape)
print(z.ndim)
print(z.size)


one=np.array([1,2,3,4,5,6])    # one Dim array
print(one.shape)
print(one.ndim)
print(one.size)

two=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])    # one Dim array
print(two.shape)
print(two.ndim)
print(two.size)



In [ ]:
# 59 create a numpy array with numpy module of in integer datatype 
import numpy as np
a1=np.array([2,3,4],dtype=int)
a1


In [ ]:
# 60 crreate a numpy array with numpy module of in float ddatatype 
import numpy as np
a1=np.array([2,3,4],dtype=float)
a1